---
title: "Analysis of Sinewave Fits"
author: "Carter Daniels"
date: "February 21, 2022"
output: html_document
---

```{r}
rm(list=ls())
#libraries
library(lme4)
library(tidyverse)
library(ggplot2)
library(rstatix)
library(BayesFactor)
library(lmerTest)
#library(qpcR)

```

```{r}
#load in data
path <- "D://Dropbox Drive Folder//Dropbox//2 All of Carter's Stuff//Carter Local//Jupyter Lab//"
raw_sinewave <- read.csv(paste(path, "raw_sinewaveFits.csv", sep=""))
norm_sinewave <- read.csv(paste(path, "sdSWfits.csv", sep=""))

raw_sinewave$Type <- "Mean"
norm_sinewave$Type <- "SD"

all_sinewave <- rbind(raw_sinewave,norm_sinewave)

all_sinewave$Group <- "B20"
all_sinewave$Group[all_sinewave$SubjectID %in% 
                     c(22,24,25,27,29,31,34,36)] <- "B40"
all_sinewave$Group[all_sinewave$SubjectID > 36] <- "B60"

all_sinewave$Group <- factor(all_sinewave$Group, levels = c("B20","B40","B60"))

all_sinewave$logB <- log(all_sinewave$B)
all_sinewave$logSm <- log(all_sinewave$Sm)
all_sinewave$logP <- log(all_sinewave$P)

all_sinewave$normB <- all_sinewave$B
all_sinewave$normB[all_sinewave$Group=="B20"] <- all_sinewave$normB[all_sinewave$Group=="B20"]/20
all_sinewave$normB[all_sinewave$Group=="B40"] <- all_sinewave$normB[all_sinewave$Group=="B40"]/40
all_sinewave$normB[all_sinewave$Group=="B60"] <- all_sinewave$normB[all_sinewave$Group=="B60"]/60

all_sinewave$normS <- all_sinewave$Sm
all_sinewave$normS[all_sinewave$Group=="B20"] <- all_sinewave$normS[all_sinewave$Group=="B20"]/15
all_sinewave$normS[all_sinewave$Group=="B40"] <- all_sinewave$normS[all_sinewave$Group=="B40"]/30
all_sinewave$normS[all_sinewave$Group=="B60"] <- all_sinewave$normS[all_sinewave$Group=="B60"]/45


all_sinewave$normP <- all_sinewave$P/20

all_sinewave$log_normB <- log(all_sinewave$normB)
all_sinewave$log_normS <- log(all_sinewave$normS)
all_sinewave$log_normP <- log(all_sinewave$normP)

```




```{r}

MEAN <- function(x){mean(x,na.rm=T)}
SEM <- function(x){sd(x,na.rm=T)/sqrt(length(x))}

sum <- all_sinewave %>% group_by(Group,Type) %>% 
  summarise(across(.cols = c(B,Sm,P), .fns = c(MEAN,SEM)))
colnames(sum) <- c("Group","Type","Bmean","Bsem","Smmean","Smsem",
                            "Pmean", "Psem")
sum
```


```{r}

sw_B_raw <- lm(logB~Group, 
               data= all_sinewave[all_sinewave$Type=="Mean",])
anova(sw_B_raw)
sw_B_raw_bayes <- lmBF(logB~Group, 
                     data=all_sinewave[all_sinewave$Type=="Mean",])
sw_B_raw_bayes@bayesFactor


sw_B_norm <- lm(log_normB~Group, 
               data= all_sinewave[all_sinewave$Type=="Mean",])
anova(sw_B_norm)
sw_B_norm_bayes <- lmBF(log_normB~Group, 
                     data=all_sinewave[all_sinewave$Type=="Mean",])
sw_B_norm_bayes@bayesFactor

```


```{r}

sw_Sm_raw <- lm(logSm~Group, 
               data= all_sinewave[all_sinewave$Type=="Mean",])
anova(sw_Sm_raw)
sw_Sm_raw_bayes <- lmBF(logSm~Group, 
                     data=all_sinewave[all_sinewave$Type=="Mean",])
sw_Sm_raw_bayes@bayesFactor


sw_Sm_norm <- lm(log_normS~Group, 
               data= all_sinewave[all_sinewave$Type=="Mean",])
anova(sw_Sm_norm)
sw_Sm_norm_bayes <- lmBF(log_normS~Group, 
                     data=all_sinewave[all_sinewave$Type=="Mean",])
sw_Sm_norm_bayes@bayesFactor

```



```{r}

norm_sum <- all_sinewave %>% group_by(Group,Type) %>% 
  summarise(across(.cols = c(normB,normS,normP), .fns = c(MEAN,SEM)))
colnames(norm_sum) <- c("Group","Type","Bmean","Bsem","Smmean","Smsem",
                            "Pmean", "Psem")
norm_sum
```


```{r}

sw_B_raw <- lm(logB~Group, 
               data= all_sinewave[all_sinewave$Type=="SD",])
anova(sw_B_raw)
sw_B_raw_bayes <- lmBF(logB~Group, 
                     data=all_sinewave[all_sinewave$Type=="SD",])
sw_B_raw_bayes@bayesFactor


sw_B_norm <- lm(log_normB~Group, 
               data= all_sinewave[all_sinewave$Type=="SD",])
anova(sw_B_norm)
sw_B_norm_bayes <- lmBF(log_normB~Group, 
                     data=all_sinewave[all_sinewave$Type=="SD",])
sw_B_norm_bayes@bayesFactor

```


```{r}

sw_Sm_raw <- lm(logSm~Group, 
               data= all_sinewave[all_sinewave$Type=="SD",])
anova(sw_Sm_raw)
sw_Sm_raw_bayes <- lmBF(logSm~Group, 
                     data=all_sinewave[all_sinewave$Type=="SD",])
sw_Sm_raw_bayes@bayesFactor


sw_Sm_norm <- lm(log_normS~Group, 
               data= all_sinewave[all_sinewave$Type=="SD",])
anova(sw_Sm_norm)
sw_Sm_norm_bayes <- lmBF(log_normS~Group, 
                     data=all_sinewave[all_sinewave$Type=="SD",])
sw_Sm_norm_bayes@bayesFactor

```